import type { Metadata } from "next";
// import { Inter } from 'next/font/google'
import "./globals.css";

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // className={inter.className}
  return (
    <html lang='en'>
      <head>
        <link
          rel='stylesheet'
          href='https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0'
        />
        <link
          href='https://{{cdn}}/prismjs@v1.x/themes/prism.css'
          rel='stylesheet'
        />
      </head>
      <body>
        {children}
        <script src='https://{{cdn}}/prismjs@v1.x/components/prism-core.min.js'></script>
        <script src='https://{{cdn}}/prismjs@v1.x/plugins/autoloader/prism-autoloader.min.js'></script>
      </body>
    </html>
  );
}
